// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEngine(arg1) {
  return window['go']['backend']['App']['AddEngine'](arg1);
}

export function CreateEngine(arg1) {
  return window['go']['backend']['App']['CreateEngine'](arg1);
}

export function DestroyEngine(arg1) {
  return window['go']['backend']['App']['DestroyEngine'](arg1);
}

export function GetEngineByFileName(arg1) {
  return window['go']['backend']['App']['GetEngineByFileName'](arg1);
}

export function GetEngineByID(arg1) {
  return window['go']['backend']['App']['GetEngineByID'](arg1);
}

export function GetEngines() {
  return window['go']['backend']['App']['GetEngines']();
}

export function GetImageData(arg1) {
  return window['go']['backend']['App']['GetImageData'](arg1);
}

export function OpenFile() {
  return window['go']['backend']['App']['OpenFile']();
}

export function Run() {
  return window['go']['backend']['App']['Run']();
}
