// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddEngine(arg1:backend.Engine):Promise<number>;

export function CreateEngine(arg1:string):Promise<backend.CreateEngineResponse>;

export function DestroyEngine(arg1:number):Promise<void>;

export function GetEngineByFileName(arg1:string):Promise<any>;

export function GetEngineByID(arg1:number):Promise<backend.EngineInfo>;

export function GetEngines():Promise<Array<backend.EngineInfo>>;

export function GetImageData(arg1:backend.Image):Promise<backend.ImageDataResponse>;

export function OpenFile():Promise<string>;

export function Run():Promise<void>;
