// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskOpenImages() {
  return window['go']['backend']['App']['AskOpenImages']();
}

export function GetEditors() {
  return window['go']['backend']['App']['GetEditors']();
}

export function Run() {
  return window['go']['backend']['App']['Run']();
}
