// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {editor} from '../models';

export function AskOpenImages():Promise<Array<editor.EditorInfo>>;

export function GetEditors():Promise<Array<editor.EditorInfo>>;

export function GetImageData(arg1:number):Promise<Array<number>>;

export function Run():Promise<void>;
