// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {editor} from '../models';

export function AskOpenImages():Promise<Array<editor.Editor>>;

export function GetEditors():Promise<Array<editor.Editor>>;

export function Run():Promise<void>;
