// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {editor} from '../models';
import {img} from '../models';
import {options} from '../models';

export function AskOpenImages():Promise<Array<editor.Editor>>;

export function DeleteEditor(arg1:number):Promise<boolean>;

export function ExportImage(arg1:img.ImageInfo,arg2:img.ImageFormat):Promise<void>;

export function FloodFill(arg1:number,arg2:number,arg3:number,arg4:options.RGBA,arg5:number):Promise<img.ImageInfo>;

export function GetEditors():Promise<Array<editor.Editor>>;

export function GetImageData(arg1:number):Promise<Array<number>>;

export function GetImageFormats():Promise<Array<img.ImageFormat>>;

export function GetImageThumbnail(arg1:number):Promise<string>;

export function ReplaceColor(arg1:number,arg2:options.RGBA,arg3:options.RGBA,arg4:number):Promise<img.ImageInfo>;

export function Run():Promise<void>;

export function SaveEditor(arg1:editor.Editor):Promise<boolean>;
