// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEngine(arg1) {
  return window['go']['app']['App']['CreateEngine'](arg1);
}

export function GetEngineByFileName(arg1) {
  return window['go']['app']['App']['GetEngineByFileName'](arg1);
}

export function GetEngineByID(arg1) {
  return window['go']['app']['App']['GetEngineByID'](arg1);
}

export function GetEngines() {
  return window['go']['app']['App']['GetEngines']();
}

export function GetImageData(arg1) {
  return window['go']['app']['App']['GetImageData'](arg1);
}

export function OpenFile() {
  return window['go']['app']['App']['OpenFile']();
}

export function Run() {
  return window['go']['app']['App']['Run']();
}
