// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {engine} from '../models';

export function CreateEngine(arg1:string):Promise<app.CreateEngineResponse>;

export function GetEngineByFileName(arg1:string):Promise<any>;

export function GetEngineByID(arg1:number):Promise<app.EngineInfo>;

export function GetEngines():Promise<Array<app.EngineInfo>>;

export function GetImageData(arg1:engine.Image):Promise<app.ImageDataResponse>;

export function OpenFile():Promise<string>;

export function Run():Promise<void>;
